name: nodejs-app-stack
version: '3.9'


services:
  nodejs-service:
    container_name: nodejs---container
    build: .
    ports:
      - "3001:3000"
  
  mongodb-service:
    container_name: mongodb---container
    image: mongo:latest
    ports:
    - "27018:27017"

  
  